spring:
  application:
    name: spring-cloud-stream-kafka-sample
  cloud:
    stream:
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        sample-topic-input:
          destination: test-topic1
          content-type: application/json
          group: group-default
          # Consumer 配置项，对应 ConsumerProperties 类
          consumer:
            max-attempts: 3 # 重试次数，默认为 3 次。
            back-off-initial-interval: 3000 # 重试间隔的初始值，单位毫秒，默认为 1000
            back-off-multiplier: 2.0 # 重试间隔的递乘系数，默认为 2.0
            back-off-max-interval: 10000 # 重试间隔的最大值，单位毫秒，默认为 10000
        sample-topic-output:
          destination: test-topic1
          content-type: application/json
      # Spring Cloud Stream Kafka 配置项
      kafka:
        # Kafka Binder 配置项，对应 KafkaBinderConfigurationProperties 类
        binder:
          brokers: localhost:9092,localhost:9093,localhost:9094
        # Kafka 自定义 Binding 配置项，对应 KafkaBindingProperties Map
        bindings:
          sample-topic-input:
            consumer:
              enable-dlq: true # 是否开启死信队列，默认为 false 关闭
              # dlq-name: # 死信队列名，默认为 `{topicName}.{consumerGroup}.errors`
          sample-topic-output:
            producer:
              sync: true  # 是否同步发送消息，默认为 false 异步


server:
  port: 8080
